language: python
python:
  - "3.4"
# command to install dependencies
before_install:
# Install ffmpeg
  - sudo apt-get update
  - sudo apt-get install -y curl
  - PROY_DIR=$(pwd)
  - cd 
  - curl -o ~/ffmpeg.tar.xz http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - tar xf ~/ffmpeg.tar.xz 
  - rm -rf ~/ffmpeg-*-static/{manpages,presets,readme.txt}
  - mkdir ~/bin
  - ls -la
  - cp ~/ffmpeg-*-static/* ~/bin
  - chmod 700 ~/bin/{ffmpeg,ffprobe,ffmpeg-10bit,qt-faststart}
  - cd && rm -rf ffmpeg{.tar.gz,-*-static}
  - PATH=$PATH:~/bin/
  - cd $PROY_DIR
# Config the xvfb server to selenium tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src/RecognitionSystem
  - make CONF=Debug
  - cd ..
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test -v 2
  - coverage run --source='.' manage.py test
after_success: coveralls
