language: python
python:
  - "3.4"
# command to install dependencies
before_install:
# Install ffmpeg
  - wget -qO ~/ffmpeg.tar.bz2 wget www.ffmpeg.org/releases/ffmpeg-2.7.1.tar.bz2
  - tar xf ~/ffmpeg.tar.gz && cd && rm -rf ffmpeg-*-static/{manpages,presets,readme.txt}
  - mkdir ~/bin
  - cp ~/ffmpeg-*-static/* ~/bin
  - chmod 700 ~/bin/{ffmpeg,ffprobe,ffmpeg-10bit,qt-faststart}
  - cd && rm -rf ffmpeg{.tar.gz,-*-static}
  - PATH=$PATH:~/bin/
# Config the xvfb server to selenium tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test -v 2
  - coverage run --source='.' manage.py test
after_success: coveralls
