language: python
python:
  - "3.4"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test
after_success: coveralls
