language: python
python:
  - "3.4"
# command to install dependencies
addons:
  apt:
    packages:
    - ffmpeg
before_install:
  - sudo apt-get install -y phantomjs
  - sudo apt-get install Xvfb
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cd src
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test -v 2
  - coverage run --source='.' manage.py test
after_success: coveralls
