language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ffmpeg
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success: coveralls
