language: python
python:
  - "3.4"
# command to install dependencies
before_install:
  - sudo apt-add-repository ppa:mc3man/trusty-media 
  - sudo apt-get update 
  - sudo apt-get install -y ffmpeg
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src
# command to run tests
script:
  - python manage.py migrate
  - python manage.py test -v 2
  - coverage run --source='.' manage.py test
after_success: coveralls
